### Create a product with wrong data
POST {{url}}/products/add
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "",
  "description": "",
  "price": -5,
  "discountPercentage": -5,
  "rating": -5,
  "stock": -5,
  "brand": "",
  "category": "",
  "thumbnail": "",
  "images": []
}

> {%
    import '../../Assertions/BadRequest'
%}
###
