### Create a product without providing a bearer token
POST {{url}}/products/add
Content-Type: application/json

{
  "title": "NewProduct",
  "description": "The new product added by the QA guy",
  "price": 60,
  "discountPercentage": 10,
  "rating": 4.25,
  "stock": 125,
  "brand": "YIOSI",
  "category": "lighting",
  "thumbnail": "https://cdn.dummyjson.com/product-images/100/thumbnail.jpg",
  "images": [
    "https://cdn.dummyjson.com/product-images/100/DOC.jpg",
    "https://cdn.dummyjson.com/product-images/100/PLANNER.jpg"
  ]
}

> {%
    import '../../Assertions/Unauthorized'
%}
###